# Generated by Django 2.0.13 on 2019-05-20 10:34

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunturi',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anunturi',
            name='facilitati',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('BA', 'Cu balcon'), ('MC', 'Mobilat complet'), ('CT', 'Centrala termica'), ('FR', 'Frigider'), ('AR', 'Aragaz'), ('MS', 'Masina de spalat')], default='', max_length=250),
        ),
    ]
