# Generated by Django 2.0.13 on 2019-05-21 12:34

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0003_auto_20190521_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunturi',
            name='compartimentare',
            field=models.CharField(choices=[('D', 'Decomandat'), ('SD', 'Semidecomandat'), ('A', 'Altceva')], default='A', max_length=20),
        ),
        migrations.AlterField(
            model_name='anunturi',
            name='descriere_anunt',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='anunturi',
            name='facilitati',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BA', 'Cu balcon'), ('MC', 'Mobilat complet'), ('CT', 'Centrala termica'), ('FR', 'Frigider'), ('AR', 'Aragaz'), ('MS', 'Masina de spalat')], max_length=250, null=True),
        ),
    ]
