# Generated by Django 2.0.13 on 2019-05-22 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0006_auto_20190522_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesaje',
            old_name='mesaj_primit',
            new_name='mesaj_client',
        ),
        migrations.RenameField(
            model_name='mesaje',
            old_name='mesaj_trimis',
            new_name='mesaj_proprietar',
        ),
    ]
